services:
  - type: web
    name: usta-go-api
    env: node
    rootDir: backend-v2
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
